### ISSUE TITLE
Use time travel in cypress tests

### ISSUE THREAD

**Issue by VB-at-Bis** [bcgov/connectivity-RTP#370] opened 2022-09-13 15:13 UTC
[https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/367 follow-up]

**Comment by matthieu-foucault** [comment] 2022-09-15 20:27
duplicate of https://github.com/bcgov/CONN-CCBC-portal/issues/485

**Closed by matthieu-foucault** 2022-09-15 20:27 UTC
